FROM python:3.13-slim

WORKDIR /app

# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Build deps for TgCrypto / llama-cpp-python (CPU)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake gcc g++ \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python -m pip install --upgrade pip \
 && pip install -r requirements.txt

COPY . .

CMD ["python", "bot/main.py"]
